name: build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Test
        run: dotnet test DemoApp/DemoApp.sln --verbosity normal

  build:
    name: build & publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.CONTAINER_REGISTRY_KEY }}

      - name: Docker build
        run: docker build DemoApp/. --tag cr.yandex/crpmoh45s6vnpdu1n8p7/demo-app:v${{github.run_number}}

      - name: Docker push
        run: docker push cr.yandex/crpmoh45s6vnpdu1n8p7/demo-app:v${{github.run_number}}
